<Project>
	<ItemGroup Label="Entity Files" Condition="'$(PkgPath)' != ''">
		<Compile Include="$(PkgPath)/PgrPgrReporting/Schemas/PgrVwAccountMetricSnapshot/PgrVwAccountMetricSnapshot.cs" Condition="Exists('$(PkgPath)/PgrPgrReporting/Schemas/PgrVwAccountMetricSnapshot/PgrVwAccountMetricSnapshot.cs')" />
		<Compile Include="$(PkgPath)/PgrPgrReporting/Schemas/PgrVwTopAccountsByBudget/PgrVwTopAccountsByBudget.cs" Condition="Exists('$(PkgPath)/PgrPgrReporting/Schemas/PgrVwTopAccountsByBudget/PgrVwTopAccountsByBudget.cs')" />
		<Compile Include="$(PkgPath)/PgrPgrReporting/Schemas/PgrVwTopNegativeDeviation/PgrVwTopNegativeDeviation.cs" Condition="Exists('$(PkgPath)/PgrPgrReporting/Schemas/PgrVwTopNegativeDeviation/PgrVwTopNegativeDeviation.cs')" />
	</ItemGroup>
</Project>