<Project>
	<ItemGroup Label="Entity Files" Condition="'$(PkgPath)' != ''">
		<Compile Include="$(PkgPath)/PgrPgrReporting/Schemas/PgrVwAccountBudgetRank/PgrVwAccountBudgetRank.cs" Condition="Exists('$(PkgPath)/PgrPgrReporting/Schemas/PgrVwAccountBudgetRank/PgrVwAccountBudgetRank.cs')" />
		<Compile Include="$(PkgPath)/PgrPgrReporting/Schemas/PgrVwAccountMetricSnapshot/PgrVwAccountMetricSnapshot.cs" Condition="Exists('$(PkgPath)/PgrPgrReporting/Schemas/PgrVwAccountMetricSnapshot/PgrVwAccountMetricSnapshot.cs')" />
		<Compile Include="$(PkgPath)/PgrPgrReporting/Schemas/PgrVwSalesManagerMetricSnapshot/PgrVwSalesManagerMetricSnapshot.cs" Condition="Exists('$(PkgPath)/PgrPgrReporting/Schemas/PgrVwSalesManagerMetricSnapshot/PgrVwSalesManagerMetricSnapshot.cs')" />
	</ItemGroup>
</Project>