<Project>
	<ItemGroup Label="Entity Files" Condition="'$(PkgPath)' != ''">
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/Account/Account.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/Account/Account.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/AccountAddress/AccountAddress.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/AccountAddress/AccountAddress.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/AccountCompetitor/AccountCompetitor.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/AccountCompetitor/AccountCompetitor.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/AccountForecast/AccountForecast.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/AccountForecast/AccountForecast.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/Activity/Activity.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/Activity/Activity.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/ActivityCategory/ActivityCategory.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/ActivityCategory/ActivityCategory.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/ActivityType/ActivityType.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/ActivityType/ActivityType.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/Calendar/Calendar.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/Calendar/Calendar.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/Contact/Contact.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/Contact/Contact.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/Contract/Contract.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/Contract/Contract.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/ContractType/ContractType.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/ContractType/ContractType.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/Country/Country.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/Country/Country.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/DayInCalendar/DayInCalendar.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/DayInCalendar/DayInCalendar.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/DayOfWeek/DayOfWeek.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/DayOfWeek/DayOfWeek.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/Lead/Lead.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/Lead/Lead.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/Opportunity/Opportunity.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/Opportunity/Opportunity.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/OpportunityCompetitor/OpportunityCompetitor.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/OpportunityCompetitor/OpportunityCompetitor.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/OpportunityProductInterest/OpportunityProductInterest.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/OpportunityProductInterest/OpportunityProductInterest.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/Order/Order.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/Order/Order.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/OrderProduct/OrderProduct.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/OrderProduct/OrderProduct.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/Pgr369BudgetCalculation/Pgr369BudgetCalculation.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/Pgr369BudgetCalculation/Pgr369BudgetCalculation.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/Pgr369Reason/Pgr369Reason.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/Pgr369Reason/Pgr369Reason.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/Pgr369ReasonGroup/Pgr369ReasonGroup.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/Pgr369ReasonGroup/Pgr369ReasonGroup.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrAccountClassification/PgrAccountClassification.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrAccountClassification/PgrAccountClassification.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrAccountLevel/PgrAccountLevel.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrAccountLevel/PgrAccountLevel.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrAccountTypesInAccount/PgrAccountTypesInAccount.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrAccountTypesInAccount/PgrAccountTypesInAccount.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrBonus/PgrBonus.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrBonus/PgrBonus.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrBonusCondition/PgrBonusCondition.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrBonusCondition/PgrBonusCondition.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrBonusThreshold/PgrBonusThreshold.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrBonusThreshold/PgrBonusThreshold.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrCompetition/PgrCompetition.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrCompetition/PgrCompetition.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrCorrectiveMeasureAction/PgrCorrectiveMeasureAction.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrCorrectiveMeasureAction/PgrCorrectiveMeasureAction.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrCountryTerritory/PgrCountryTerritory.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrCountryTerritory/PgrCountryTerritory.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrCustomerlabel/PgrCustomerlabel.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrCustomerlabel/PgrCustomerlabel.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrCustomerThresholdMatrix/PgrCustomerThresholdMatrix.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrCustomerThresholdMatrix/PgrCustomerThresholdMatrix.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrDeliveryTimesAccountAddress/PgrDeliveryTimesAccountAddress.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrDeliveryTimesAccountAddress/PgrDeliveryTimesAccountAddress.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrDeviationReasonCode/PgrDeviationReasonCode.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrDeviationReasonCode/PgrDeviationReasonCode.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrEBox/PgrEBox.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrEBox/PgrEBox.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrErpSystem/PgrErpSystem.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrErpSystem/PgrErpSystem.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrExecuteSQLErrorLog/PgrExecuteSQLErrorLog.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrExecuteSQLErrorLog/PgrExecuteSQLErrorLog.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrGroupAffiliation/PgrGroupAffiliation.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrGroupAffiliation/PgrGroupAffiliation.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrIsVertIntegrated/PgrIsVertIntegrated.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrIsVertIntegrated/PgrIsVertIntegrated.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrOdataLog/PgrOdataLog.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrOdataLog/PgrOdataLog.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrPerformance/PgrPerformance.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrPerformance/PgrPerformance.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrPlant/PgrPlant.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrPlant/PgrPlant.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrPlantAccountAddress/PgrPlantAccountAddress.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrPlantAccountAddress/PgrPlantAccountAddress.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrPowerBI/PgrPowerBI.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrPowerBI/PgrPowerBI.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrPowerBiSlicer/PgrPowerBiSlicer.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrPowerBiSlicer/PgrPowerBiSlicer.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrPowerBiSlicerValue/PgrPowerBiSlicerValue.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrPowerBiSlicerValue/PgrPowerBiSlicerValue.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrPowerBiUserFilter/PgrPowerBiUserFilter.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrPowerBiUserFilter/PgrPowerBiUserFilter.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrTeam/PgrTeam.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrTeam/PgrTeam.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrVisitReason/PgrVisitReason.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrVisitReason/PgrVisitReason.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrVisitReport/PgrVisitReport.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrVisitReport/PgrVisitReport.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrVisitType/PgrVisitType.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrVisitType/PgrVisitType.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/PgrYear/PgrYear.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/PgrYear/PgrYear.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/Product/Product.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/Product/Product.cs')" />
		<Compile Include="$(PkgPath)/Pgr.Core/Schemas/Territory/Territory.cs" Condition="Exists('$(PkgPath)/Pgr.Core/Schemas/Territory/Territory.cs')" />
	</ItemGroup>
</Project>