<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
		<CoreTargetFramework Condition="'$(CoreTargetFramework)' == ''">net472</CoreTargetFramework>
		<TargetFramework>$(CoreTargetFramework)</TargetFramework>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DebugSymbols>false</DebugSymbols>
		<DebugType>pdbonly</DebugType>
		<Optimize>true</Optimize>
		<MSBuildWarningsAsMessages>MSB3277;MSB3245;MSB3243</MSBuildWarningsAsMessages>
		<NoWarn>CS1522,CS0162</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<AssemblyAttribute Include="Terrasoft.Core.Attributes.PackageReferenceAssemblyAttribute">
			<_Parameter1>All</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
	<PropertyGroup Label="Path">
		<RelativeCurrentPkgFolderPath Condition="'$(RelativeCurrentPkgFolderPath)' == ''">../</RelativeCurrentPkgFolderPath>
		<RelativePkgFolderPath Condition="'$(RelativePkgFolderPath)' == ''">$(RelativeCurrentPkgFolderPath)..</RelativePkgFolderPath>
		<ConfLibPath Condition="'$(ConfLibPath)' == ''">$(RelativePkgFolderPath)/../Lib</ConfLibPath>
	</PropertyGroup>
	<Choose>
		<When Condition="'$(TargetFramework)' == 'net472'">
			<PropertyGroup>
				<CoreLibPath Condition="'$(CoreLibPath)' == ''">$(RelativePkgFolderPath)/../../bin</CoreLibPath>
				<StandalonePackageAssemblyPath Condition="'$(StandalonePackageAssemblyPath)' == ''">Files/Bin</StandalonePackageAssemblyPath>
			</PropertyGroup>
		</When>
		<When Condition="'$(TargetFramework)' == 'netstandard2.0'">
			<PropertyGroup>
				<CoreLibPath Condition="'$(CoreLibPath)' == ''">$(RelativePkgFolderPath)/../..</CoreLibPath>
				<MSBuildWarningsAsMessages Condition=" '$(Configuration)' == 'Release' ">MSB3277;MSB3245;MSB3243</MSBuildWarningsAsMessages>
				<StandalonePackageAssemblyPath Condition="'$(StandalonePackageAssemblyPath)' == ''">Files/Bin/netstandard</StandalonePackageAssemblyPath>
			</PropertyGroup>
		</When>
	</Choose>
	<PropertyGroup>
		<OutputPath>$(RelativeCurrentPkgFolderPath)$(StandalonePackageAssemblyPath)</OutputPath>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="$(RelativeCurrentPkgFolderPath)Schemas/**/*.cs" Condition="'$(RelativeCurrentPkgFolderPath)' != ''" />
		<Compile Include="$(RelativeCurrentPkgFolderPath)Autogenerated/Src/**/*.cs" Condition="'$(RelativeCurrentPkgFolderPath)' != ''" />
		<Compile Remove="$(RelativeCurrentPkgFolderPath)Assemblies/**" />
		<Compile Remove="$(RelativeCurrentPkgFolderPath)Data/**" />
		<Compile Remove="$(RelativeCurrentPkgFolderPath)SqlScripts/**" />
		<Compile Remove="$(RelativeCurrentPkgFolderPath)Resources/**" />
		<Compile Remove="$(RelativeCurrentPkgFolderPath)Schemas/**/*.json" />
		<EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)Schemas/**/*.json" />
		<EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)Assemblies/**" />
		<EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)Data/**" />
		<EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)SqlScripts/**" />
		<EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)Schemas/**" />
		<EmbeddedResource Remove="$(RelativeCurrentPkgFolderPath)Resources/**" />
		<None Remove="$(RelativeCurrentPkgFolderPath)Schemas/**/*.json" />
		<None Remove="$(RelativeCurrentPkgFolderPath)Assemblies/**" />
		<None Remove="$(RelativeCurrentPkgFolderPath)Data/**" />
		<None Remove="$(RelativeCurrentPkgFolderPath)SqlScripts/**" />
		<None Remove="$(RelativeCurrentPkgFolderPath)Resources/**" />
	</ItemGroup>
	<ItemGroup Label="Package Assembly References">
		<Reference Include="$(RelativeCurrentPkgFolderPath)Assemblies/*/*.dll">
			<Private>False</Private>
		</Reference>
		<Reference Include="$(RelativeCurrentPkgFolderPath)Autogenerated/Lib/*.dll">
			<Private>False</Private>
		</Reference>
	</ItemGroup>
	<Choose>
		<When Condition="'$(TargetFramework)' == 'net472'">
			<ItemGroup>
				<Reference Include="System.ServiceModel" />
				<Reference Include="System.ServiceModel.Activation" />
				<Reference Include="System.ServiceModel.Web" />
				<Reference Include="System.Web" />
			</ItemGroup>
			<ItemGroup Label="Core References">
				<Reference Include="Terrasoft.Reports">
					<HintPath>$(CoreLibPath)/Terrasoft.Reports.dll</HintPath>
					<SpecificVersion>False</SpecificVersion>
					<Private>False</Private>
				</Reference>
				<Reference Include="Terrasoft.GoogleServices">
					<HintPath>$(CoreLibPath)/Terrasoft.GoogleServices.dll</HintPath>
					<SpecificVersion>False</SpecificVersion>
					<Private>False</Private>
				</Reference>
			</ItemGroup>
		</When>
		<When Condition="'$(TargetFramework)' == 'netstandard2.0'">
			<ItemGroup Label="Core References">
				<Reference Include="Terrasoft.Messaging.Common.Standard">
					<HintPath>$(CoreLibPath)/Terrasoft.Messaging.Common.Standard.dll</HintPath>
					<SpecificVersion>False</SpecificVersion>
					<Private>False</Private>
				</Reference>
				<Reference Include="Terrasoft.ServiceModel.Primitives">
					<HintPath>$(CoreLibPath)/Terrasoft.ServiceModel.Primitives.dll</HintPath>
					<SpecificVersion>False</SpecificVersion>
					<Private>False</Private>
				</Reference>
			</ItemGroup>
		</When>
	</Choose>
	<ItemGroup Label="Core References">
		<Reference Include="Common.Logging">
			<HintPath>$(CoreLibPath)/Common.Logging.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Common.Logging.Core">
			<HintPath>$(CoreLibPath)/Common.Logging.Core.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Creatio.Copilot.Abstractions">
			<HintPath>$(CoreLibPath)/Creatio.Copilot.Abstractions.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Creatio.FeatureToggling">
			<HintPath>$(CoreLibPath)/Creatio.FeatureToggling.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Authentication">
			<HintPath>$(CoreLibPath)/Terrasoft.Authentication.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Authentication.Contract">
			<HintPath>$(CoreLibPath)/Terrasoft.Authentication.Contract.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Common">
			<HintPath>$(CoreLibPath)/Terrasoft.Common.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.ComponentSpace.Interfaces">
			<HintPath>$(CoreLibPath)/Terrasoft.ComponentSpace.Interfaces.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Core">
			<HintPath>$(CoreLibPath)/Terrasoft.Core.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Core.Applications">
			<HintPath>$(CoreLibPath)/Terrasoft.Core.Applications.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Core.ConfigurationBuild">
			<HintPath>$(CoreLibPath)/Terrasoft.Core.ConfigurationBuild.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Core.Packages">
			<HintPath>$(CoreLibPath)/Terrasoft.Core.Packages.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Core.Process">
			<HintPath>$(CoreLibPath)/Terrasoft.Core.Process.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Core.Scheduler">
			<HintPath>$(CoreLibPath)/Terrasoft.Core.Scheduler.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Core.ServiceModelContract">
			<HintPath>$(CoreLibPath)/Terrasoft.Core.ServiceModelContract.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Core.Translation">
			<HintPath>$(CoreLibPath)/Terrasoft.Core.Translation.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.ElasticSearch">
			<HintPath>$(CoreLibPath)/Terrasoft.ElasticSearch.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.File">
			<HintPath>$(CoreLibPath)/Terrasoft.File.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.File.Abstractions">
			<HintPath>$(CoreLibPath)/Terrasoft.File.Abstractions.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.GlobalSearch">
			<HintPath>$(CoreLibPath)/Terrasoft.GlobalSearch.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.GoogleServerConnector">
			<HintPath>$(CoreLibPath)/Terrasoft.GoogleServerConnector.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.IO">
			<HintPath>$(CoreLibPath)/Terrasoft.IO.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Messaging.Common">
			<HintPath>$(CoreLibPath)/Terrasoft.Messaging.Common.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Messaging.Common.Standard">
			<HintPath>$(CoreLibPath)/Terrasoft.Messaging.Common.Standard.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Mobile">
			<HintPath>$(CoreLibPath)/Terrasoft.Mobile.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Monitoring">
			<HintPath>$(CoreLibPath)/Terrasoft.Monitoring.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.NewtonsoftWrapper">
			<HintPath>$(CoreLibPath)/Terrasoft.NewtonsoftWrapper.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Nui">
			<HintPath>$(CoreLibPath)/Terrasoft.Nui.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Nui.ServiceModel">
			<HintPath>$(CoreLibPath)/Terrasoft.Nui.ServiceModel.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.OAuthIntegration">
			<HintPath>$(CoreLibPath)/Terrasoft.OAuthIntegration.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Reports">
			<HintPath>$(CoreLibPath)/Terrasoft.Reports.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.ServiceBus">
			<HintPath>$(CoreLibPath)/Terrasoft.ServiceBus.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.ServiceBus.Abstractions">
			<HintPath>$(CoreLibPath)/Terrasoft.ServiceBus.Abstractions.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Services">
			<HintPath>$(CoreLibPath)/Terrasoft.Services.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.SmsIntegration">
			<HintPath>$(CoreLibPath)/Terrasoft.SmsIntegration.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Social">
			<HintPath>$(CoreLibPath)/Terrasoft.Social.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Sync">
			<HintPath>$(CoreLibPath)/Terrasoft.Sync.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.UI.Common">
			<HintPath>$(CoreLibPath)/Terrasoft.UI.Common.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Web.Common">
			<HintPath>$(CoreLibPath)/Terrasoft.Web.Common.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Web.FileSecurity">
			<HintPath>$(CoreLibPath)/Terrasoft.Web.FileSecurity.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Web.Http.Abstractions">
			<HintPath>$(CoreLibPath)/Terrasoft.Web.Http.Abstractions.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Web.Security">
			<HintPath>$(CoreLibPath)/Terrasoft.Web.Security.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
	</ItemGroup>
	<ItemGroup Label="Package References">
		<Reference Include="CrtC360InUiV2">
			<HintPath>$(RelativePkgFolderPath)/CrtC360InUiV2/$(StandalonePackageAssemblyPath)/CrtC360InUiV2.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="CrtCasesInC360">
			<HintPath>$(RelativePkgFolderPath)/CrtCasesInC360/$(StandalonePackageAssemblyPath)/CrtCasesInC360.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="CrtCore">
			<HintPath>$(RelativePkgFolderPath)/CrtCore/$(StandalonePackageAssemblyPath)/CrtCore.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="CrtDigitalAdsInLeadGen">
			<HintPath>$(RelativePkgFolderPath)/CrtDigitalAdsInLeadGen/$(StandalonePackageAssemblyPath)/CrtDigitalAdsInLeadGen.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="CrtLeadOppMgmtInC360">
			<HintPath>$(RelativePkgFolderPath)/CrtLeadOppMgmtInC360/$(StandalonePackageAssemblyPath)/CrtLeadOppMgmtInC360.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="CrtMeetingInsights">
			<HintPath>$(RelativePkgFolderPath)/CrtMeetingInsights/$(StandalonePackageAssemblyPath)/CrtMeetingInsights.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="CrtOrderContractCopilot">
			<HintPath>$(RelativePkgFolderPath)/CrtOrderContractCopilot/$(StandalonePackageAssemblyPath)/CrtOrderContractCopilot.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="CrtTouchInWebForm">
			<HintPath>$(RelativePkgFolderPath)/CrtTouchInWebForm/$(StandalonePackageAssemblyPath)/CrtTouchInWebForm.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="CrtTouchPointInLead">
			<HintPath>$(RelativePkgFolderPath)/CrtTouchPointInLead/$(StandalonePackageAssemblyPath)/CrtTouchPointInLead.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="CrtWaterfallPipelineInLeadOppMgmt">
			<HintPath>$(RelativePkgFolderPath)/CrtWaterfallPipelineInLeadOppMgmt/$(StandalonePackageAssemblyPath)/CrtWaterfallPipelineInLeadOppMgmt.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
		<Reference Include="Terrasoft.Configuration">
			<HintPath>$(RelativePkgFolderPath)/../bin/Terrasoft.Configuration.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
			<Private>False</Private>
		</Reference>
	</ItemGroup>
	<ItemGroup Label="Standalone package external assembly references" />
	<ItemGroup Label="Entity Files">
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/Account/Account.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/Account/Account.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/AccountAddress/AccountAddress.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/AccountAddress/AccountAddress.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/AccountCompetitor/AccountCompetitor.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/AccountCompetitor/AccountCompetitor.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/AccountForecast/AccountForecast.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/AccountForecast/AccountForecast.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/Activity/Activity.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/Activity/Activity.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/ActivityCategory/ActivityCategory.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/ActivityCategory/ActivityCategory.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/ActivityType/ActivityType.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/ActivityType/ActivityType.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/Calendar/Calendar.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/Calendar/Calendar.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/Contact/Contact.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/Contact/Contact.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/Contract/Contract.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/Contract/Contract.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/ContractType/ContractType.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/ContractType/ContractType.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/Country/Country.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/Country/Country.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/DayInCalendar/DayInCalendar.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/DayInCalendar/DayInCalendar.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/DayOfWeek/DayOfWeek.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/DayOfWeek/DayOfWeek.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/Lead/Lead.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/Lead/Lead.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/Opportunity/Opportunity.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/Opportunity/Opportunity.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/OpportunityCompetitor/OpportunityCompetitor.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/OpportunityCompetitor/OpportunityCompetitor.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/OpportunityProductInterest/OpportunityProductInterest.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/OpportunityProductInterest/OpportunityProductInterest.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/Order/Order.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/Order/Order.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/OrderProduct/OrderProduct.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/OrderProduct/OrderProduct.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/Pgr369BudgetCalculation/Pgr369BudgetCalculation.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/Pgr369BudgetCalculation/Pgr369BudgetCalculation.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/Pgr369Reason/Pgr369Reason.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/Pgr369Reason/Pgr369Reason.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/Pgr369ReasonGroup/Pgr369ReasonGroup.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/Pgr369ReasonGroup/Pgr369ReasonGroup.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrAccountClassification/PgrAccountClassification.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrAccountClassification/PgrAccountClassification.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrAccountLevel/PgrAccountLevel.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrAccountLevel/PgrAccountLevel.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrAccountTypesInAccount/PgrAccountTypesInAccount.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrAccountTypesInAccount/PgrAccountTypesInAccount.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrBonus/PgrBonus.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrBonus/PgrBonus.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrBonusCondition/PgrBonusCondition.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrBonusCondition/PgrBonusCondition.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrBonusThreshold/PgrBonusThreshold.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrBonusThreshold/PgrBonusThreshold.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrCompetition/PgrCompetition.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrCompetition/PgrCompetition.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrCorrectiveMeasureAction/PgrCorrectiveMeasureAction.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrCorrectiveMeasureAction/PgrCorrectiveMeasureAction.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrCountryTerritory/PgrCountryTerritory.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrCountryTerritory/PgrCountryTerritory.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrCustomerlabel/PgrCustomerlabel.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrCustomerlabel/PgrCustomerlabel.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrCustomerProject/PgrCustomerProject.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrCustomerProject/PgrCustomerProject.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrCustomerThresholdMatrix/PgrCustomerThresholdMatrix.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrCustomerThresholdMatrix/PgrCustomerThresholdMatrix.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrDeliveryTimesAccountAddress/PgrDeliveryTimesAccountAddress.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrDeliveryTimesAccountAddress/PgrDeliveryTimesAccountAddress.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrDeviationReasonCode/PgrDeviationReasonCode.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrDeviationReasonCode/PgrDeviationReasonCode.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrEBox/PgrEBox.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrEBox/PgrEBox.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrErpSystem/PgrErpSystem.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrErpSystem/PgrErpSystem.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrExecuteSQLErrorLog/PgrExecuteSQLErrorLog.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrExecuteSQLErrorLog/PgrExecuteSQLErrorLog.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrGroupAffiliation/PgrGroupAffiliation.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrGroupAffiliation/PgrGroupAffiliation.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrIsVertIntegrated/PgrIsVertIntegrated.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrIsVertIntegrated/PgrIsVertIntegrated.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrOdataLog/PgrOdataLog.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrOdataLog/PgrOdataLog.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrPerformance/PgrPerformance.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrPerformance/PgrPerformance.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrPlant/PgrPlant.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrPlant/PgrPlant.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrPlantAccountAddress/PgrPlantAccountAddress.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrPlantAccountAddress/PgrPlantAccountAddress.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrPowerBI/PgrPowerBI.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrPowerBI/PgrPowerBI.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrPowerBiSlicer/PgrPowerBiSlicer.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrPowerBiSlicer/PgrPowerBiSlicer.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrPowerBiSlicerValue/PgrPowerBiSlicerValue.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrPowerBiSlicerValue/PgrPowerBiSlicerValue.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrPowerBiUserFilter/PgrPowerBiUserFilter.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrPowerBiUserFilter/PgrPowerBiUserFilter.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrProjectPrice/PgrProjectPrice.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrProjectPrice/PgrProjectPrice.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrProjectPriceRule/PgrProjectPriceRule.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrProjectPriceRule/PgrProjectPriceRule.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrTeam/PgrTeam.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrTeam/PgrTeam.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrVisitReason/PgrVisitReason.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrVisitReason/PgrVisitReason.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrVisitReport/PgrVisitReport.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrVisitReport/PgrVisitReport.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrVisitType/PgrVisitType.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrVisitType/PgrVisitType.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrYear/PgrYear.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/PgrYear/PgrYear.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/Product/Product.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/Product/Product.cs')" />
		<Compile Remove="$(RelativePkgFolderPath)/Pgr.Core/Schemas/Territory/Territory.cs" Condition="Exists('$(RelativePkgFolderPath)/Pgr.Core/Schemas/Territory/Territory.cs')" />
	</ItemGroup>
	<ItemGroup Label="3rd Party References"></ItemGroup>
	<Target Name="Paths" BeforeTargets="BeforeCompile">
		<Message Importance="High" Text="*********** Project [$(MSBuildProjectFile)] TargetFramework [$(TargetFramework)] CoreTargetFramework [$(CoreTargetFramework)]" />
		<!--
		<Message Importance="High" Text="*********** CoreLibPath [$(CoreLibPath)]" />
		<Message Importance="High" Text="*********** RelativeCurrentPkgFolderPath [$(RelativeCurrentPkgFolderPath)]" />
		<Message Importance="High" Text="*********** RelativePkgFolderPath [$(RelativePkgFolderPath)]" />
		<Message Importance="High" Text="*********** StandalonePackageAssemblyPath [$(StandalonePackageAssemblyPath)]" />
		<Message Importance="High" Text="*********** OutputPath [$(OutputPath)]" />
		-->
		<Message Importance="High" Text="*********** CoreLibPath [$([System.IO.Path]::GetFullPath('$(CoreLibPath)'))]" />
		<Message Importance="High" Text="*********** RelativeCurrentPkgFolderPath [$([System.IO.Path]::GetFullPath('$(RelativeCurrentPkgFolderPath)'))]" />
		<Message Importance="High" Text="*********** RelativePkgFolderPath [$([System.IO.Path]::GetFullPath('$(RelativePkgFolderPath)'))]" />
		<Message Importance="High" Text="*********** StandalonePackageAssemblyPath [$([System.IO.Path]::GetFullPath('$(StandalonePackageAssemblyPath)'))]" />
		<Message Importance="High" Text="*********** OutputPath [$([System.IO.Path]::GetFullPath('$(OutputPath)'))]" />
	</Target>
</Project>